packages:
  - apps/*
  - packages/*
  - contracts

allowBuilds:
  esbuild: true
  unrs-resolver: true

overrides:
  esbuild: 0.28.1
  typescript: 6.0.3

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
